export const Products = [
  {
    id: 1,
    name: "Ovida Bat Sunglasses Designer Gothic Shades",
    price: 9.99,
    originalPrice: 19.99,
    image: "https://m.media-amazon.com/images/I/51NHiMcy5DL._AC_SX679_.jpg",
    images: [
      "https://m.media-amazon.com/images/I/41hvQElzJzL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/61CL+FCQGQL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/61dGXFSx3SL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/51NHiMcy5DL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/51QJ9v7O5lL._AC_SX679_.jpg",
    ],
    description:
      "Rimless bat sunglasses show your unique and fashion, a must for Y2K and GOTHIC girls. Novelty trendy bat sunglasses makes you more eye-catching in the crowd. The steam punk glasses are the must-have accessory to accent this following Halloween cosplay party, show your special at the party",
    category: "Women's Accessories",
    rating: 4.4,
    reviews: "2.3k",
    inStock: true,
    affiliateLink: "https://amzn.to/3U0iHoM",
    // stockCount: 15,
    // brand: "AudioTech",
    // features: [
    //   "Noise Cancellation",
    //   "30h Battery",
    //   "Wireless",
    //   "Premium Sound",
    // ],
    // discount: 25,
  },
  {
    id: 2,
    name: "Women's Halloween Costume Long Dress",
    price: 17.99,
    originalPrice: 28.99,
    image: "https://m.media-amazon.com/images/I/61oz2yKugpL._AC_SX569_.jpg",
    images: [
      "https://m.media-amazon.com/images/I/71kjGaQbPrL._AC_SX569_.jpg",
      "https://m.media-amazon.com/images/I/71X0scdAvfL._AC_SX569_.jpg",
      "https://m.media-amazon.com/images/I/61dGXFSx3SL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/61EXIvT-A8L._AC_SX569_.jpg",
    ],
    description:
      "Premium Quality Fabric: Our vintage dress for Halloween carnival party is crafted from a blend of 95% Polyester and 5% Spandex, ensuring a soft and comfortable fit. It's gentle on the skin and breathable, making it perfect for extended wear.",
    category: "Women's Fashions",
    rating: 4.4,
    reviews: "93",
    inStock: true,
    affiliateLink: "https://amzn.to/4lNBRud",
  },
  {
    id: 3,
    name: "Leg Avenue Women's Large Ruched Witch Hat",
    price: 30.99,
    originalPrice: 49.99,
    image: "https://m.media-amazon.com/images/I/712MOXPWsgL._AC_SY741_.jpg",
    images: [
      "https://m.media-amazon.com/images/I/61dPneMF1OL._AC_SY741_.jpg",
      "https://m.media-amazon.com/images/I/71GGfC8nxNL._AC_SY741_.jpg",
    ],
    description:
      "No love potions required to fall head over heels for the enchanting Leg Avenue Ruched Witch Hat, featuring a whimsical ruched top design, curved brim, and matte satin fabric",
    category: "Women's Accessories",
    rating: 4.4,
    reviews: "1.5k",
    inStock: true,
    affiliateLink: "https://amzn.to/4kY3ks0",
  },
  {
    id: 4,
    name: "KKG Tops Tunics for Women to Wear with Leggings",
    price: 19.99,
    originalPrice: 25.99,
    image: "https://m.media-amazon.com/images/I/514CJOlsd4L._AC_SX679_.jpg",
    images: [
      "https://m.media-amazon.com/images/I/612L1GSISEL._AC_SX522_.jpg",
      "https://m.media-amazon.com/images/I/516FqmHWMwL._AC_SX569_.jpg",
      "https://m.media-amazon.com/images/I/41gqY5A-fBL._AC_SX569_.jpg",
      "https://m.media-amazon.com/images/I/41gqY5A-fBL._AC_SX569_.jpg",
    ],
    description:
      "Feature: Round Neck, Short sleeves cute tee, tunic tops to wear with leggings, long tops to wear with leggings, casual long tunics tops to wear with leggings, tunics or tops to wear with leggings, Plus Size.",
    category: "Women's Fashions",
    rating: 4.3,
    reviews: "1.3k",
    inStock: true,
    affiliateLink: "https://amzn.to/44Xxh5i",
  },
  {
    id: 5,
    name: "Halloween Pumpkin Costume for Women",
    price: 14.99,
    originalPrice: 20.99,
    image: "https://m.media-amazon.com/images/I/61d6JVkYBsL._AC_SY879_.jpg",
    images: [
      "https://m.media-amazon.com/images/I/81j8y7SR0rL._AC_SX522_.jpg",
      "https://m.media-amazon.com/images/I/71w2cCiOe1L._AC_SX522_.jpg",
      "https://m.media-amazon.com/images/I/71eqf3RIPQL._AC_SX522_.jpg",
      "https://m.media-amazon.com/images/I/71Gs0CJ+v+L._AC_SX522_.jpg",
      "https://m.media-amazon.com/images/I/71+FPNkTdJL._AC_SX522_.jpg",
    ],
    description:
      "Quality Material: This pumpkin costume for women is made of polyester,the fabric flows nicely, lightweight and comfortable.",
    category: "Women's Fashions",
    rating: 4.4,
    reviews: "502",
    inStock: true,
    affiliateLink: "https://amzn.to/4lSFnDG",
  },
  {
    id: 6,
    name: "Morph Skeleton Costume Women",
    price: 34.95,
    originalPrice: 51.99,
    image: "https://m.media-amazon.com/images/I/71qqhUYm6QL._AC_SX679_.jpg",
    images: [
      "https://m.media-amazon.com/images/I/71G36ikZEyL._AC_SX522_.jpg",
      "https://m.media-amazon.com/images/I/61RFjIJHK2L._AC_SX522_.jpg",
      "https://m.media-amazon.com/images/I/71Qh5Bdu7RL._AC_SX522_.jpg",
    ],
    description:
      "Our women skeleton costume includes: One black skeleton printed jumpsuit with hood, pockets and elastic cuffs.",
    category: "Women's Fashions",
    rating: 3.6,
    reviews: "78",
    inStock: true,
    affiliateLink: "https://amzn.to/3UuKU7k",
  },
  {
    id: 7,
    name: "Women Halloween Shirt Hocus Pocus Shirt",
    price: 13.99,
    originalPrice: 17.99,
    image: "https://m.media-amazon.com/images/I/81er-yAJsjL._AC_SY550_.jpg",
    images: [
      "https://m.media-amazon.com/images/I/81HA3F72PvL._AC_SY550_.jpg",
      "https://m.media-amazon.com/images/I/81MJAYHUZeL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/81eseHslidL._AC_SX522_.jpg",
    ],
    description:
      "This halloween sanderson t shirt is cotton blend ,which let it be soft, comfortable, lightweight and breathable. this scary movies splicing tee top washes and wears well.the fabric is stretchy , the graphics will still stuck around through many washes.",
    category: "Women's Fashions",
    rating: 4.6,
    reviews: "1k",
    inStock: true,
    affiliateLink: "https://amzn.to/3GMlX4d",
  },
  {
    id: 8,
    name: "Maleficent Christening Gown Costume",
    price: 47.5,
    originalPrice: 75.99,
    image: "https://m.media-amazon.com/images/I/81aNvdNWr0L._AC_SY550_.jpg",
    images: [
      "https://m.media-amazon.com/images/I/81uXbpC1-3L._AC_SY550_.jpg",
      "https://m.media-amazon.com/images/I/71afuoHp4dL._AC_SY550_.jpg",
    ],
    description:
      "Dress with detachable brooch and character headpiece. Whether it's Halloween, birthday parties, or even a fun filled night, disguise is good for everything.",
    category: "Women's Fashions",
    rating: 4.1,
    reviews: "2.6k",
    inStock: true,
    affiliateLink: "https://amzn.to/4199eiH",
  },
  {
    id: 9,
    name: "Rubies womens Supergirl Tv Show Costume Dress",
    price: 47.5,
    originalPrice: 75.99,
    image: "https://m.media-amazon.com/images/I/71Gai2YktZL._AC_SY445_.jpg",
    images: [
      "https://m.media-amazon.com/images/I/8152rFL5meL._AC_SX342_.jpg",
      "https://m.media-amazon.com/images/I/71voi27260L._AC_SX342_.jpg",
      "https://m.media-amazon.com/images/I/71H0fsPOYHL._AC_SX385_.jpg",
      "https://m.media-amazon.com/images/I/71GbxGUVJnL._AC_SX385_.jpg",
      "https://m.media-amazon.com/images/I/81mq98U50CL._AC_SX342_.jpg",
    ],
    description:
      "EVERY DAY IS AN OCCASION: Great for Halloween, themed parties, or cosplay events. Life is more fun in costume. COSTUME DESTINATION: Rubies aims to spark joy and creativity as your go-to destination for expertly crafted costumes & accessories.",
    category: "Women's Fashions",
    rating: 4.4,
    reviews: "1.6k",
    inStock: true,
    affiliateLink: "https://amzn.to/46vxrU2",
  },
  {
    id: 10,
    name: "Inflatable Shark Costume for Adult(Kids) Funny Halloween Costumes",
    price: 29.99,
    originalPrice: 37.59,
    image: "https://m.media-amazon.com/images/I/41uEZOjiFbL._AC_SX679_.jpg",
    images: [
      "https://m.media-amazon.com/images/I/51ZHSAx0RqL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/51olry1FIzL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/61zFk06SnML._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/61UHN9hzbUL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/61xIWQE5K0L._AC_SX679_.jpg",
    ],
    description:
      "The Inflatable Costumes is One Size Fit for unisex adult for 5.3ft-6ft, you can big hit in the crowds, easy set up and move that you will be the luminous point among the crowd, will brings many happiness for you and your friends.",
    category: "Women's Fashions",
    rating: 4.4,
    reviews: "525",
    inStock: true,
    affiliateLink: "https://amzn.to/4oeOiB8",
  },
  {
    id: 11,
    name: "Alien Costume Adult Inflatable Costume Blow Up Costume Ride On Suit",
    price: 29.99,
    originalPrice: 37.59,
    image: "https://m.media-amazon.com/images/I/51DafDUX4CL._AC_SX679_.jpg",
    images: [
      "https://m.media-amazon.com/images/I/51zAKX48hcL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/51cnHFk-H3L._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/51FKfWTx9GL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/71EFRKBagxL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/712nXDuZ8NL._AC_SX679_.jpg",
    ],
    description:
      "Wear inflatable alien costume adult for Halloween festivities! It is certainly the eye-catching alien inflatable costume that make the level of joy on Halloween exponentially increase.",
    category: "Men's Fashions",
    rating: 4.4,
    reviews: "139",
    inStock: true,
    affiliateLink: "https://amzn.to/3H4qbUO",
  },
  {
    id: 12,
    name: "Adult Pirate Shirt Vest Viking Pants Hat Set for Halloween Themed Parties",
    price: 38.99,
    originalPrice: 48.91,
    image: "https://m.media-amazon.com/images/I/81wJE+g4cmL._AC_SY550_.jpg",
    images: [
      "https://m.media-amazon.com/images/I/71eWqcqRaQL._AC_SY550_.jpg",
      "https://m.media-amazon.com/images/I/71hAaAUK4UL._AC_SX522_.jpg",
      "https://m.media-amazon.com/images/I/71uaVIvT6YL._AC_SX522_.jpg",
      "https://m.media-amazon.com/images/I/71EFRKBagxL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/71snrLKoNBL._AC_SX522_.jpg",
      "https://m.media-amazon.com/images/I/81kUlJp8+gL._AC_SY550_.jpg",
      "https://m.media-amazon.com/images/I/81JjpxRZKpL._AC_SX425_.jpg",
    ],
    description:
      "This Pirate Costume for Men Includes 1 Hat, 1 Vest, 1 Shirt, 1 Sash, 1 Bandana, 1 Pair of Pants, 1 Pair of Shoe Covers.",
    category: "Men's Fashions",
    rating: 4.4,
    reviews: "1.6k",
    inStock: true,
    affiliateLink: "https://amzn.to/4mgKvBs",
  },
  {
    id: 13,
    name: "Tunic Hooded Robe Halloween Cosplay Costume Robe Cloak Cape",
    price: 12.99,
    originalPrice: 18.91,
    image: "https://m.media-amazon.com/images/I/51sW+3OcnKL._AC_SY550_.jpg",
    images: [
      "https://m.media-amazon.com/images/I/41km3axLoUL._AC_SY550_.jpg",

      "https://m.media-amazon.com/images/I/51sVSyumUML._AC_SY550_.jpg",
    ],
    description:
      "Mens Halloween Witch Cosplay Robe Costume Adult Hooded Cloak Cape.",
    category: "Men's Fashions",
    rating: 4.3,
    reviews: "4.6k",
    inStock: true,
    affiliateLink: "https://amzn.to/44SmnPL",
  },
  {
    id: 14,
    name: "The Nun Movie Deluxe Men's Costume",
    price: 31.99,
    originalPrice: 50.99,
    image: "https://m.media-amazon.com/images/I/51hqCPQSfkL._AC_SY550_.jpg",
    images: [
      "https://m.media-amazon.com/images/I/718UYdTJ9SL._AC_SX522_.jpg",
      "https://m.media-amazon.com/images/I/71QAbT6NGvL._AC_SX522_.jpg",
    ],
    description:
      "The Nun deluxe costume; look for trademark on label and package to help assure you've received the authentic, safety-tested item.",
    category: "Men's Fashions",
    rating: 4.5,
    reviews: "1k",
    inStock: true,
    affiliateLink: "https://amzn.to/4o82gV9",
  },
  {
    id: 15,
    name: "Nightmare Clown Costume Design",
    price: 34.99,
    originalPrice: 44.99,
    image: "https://m.media-amazon.com/images/I/81Kh8ea8DZL._AC_SY550_.jpg",
    images: [],
    description:
      "TShirt has hook & loop fastener at back of neck, elastic at gathered sleeve cuffs.",
    category: "Men's Fashions",
    rating: 4.5,
    reviews: "985",
    inStock: true,
    affiliateLink: "https://amzn.to/4lRVgdA",
  },
  {
    id: 16,
    name: "Creations Brave Men’s Roman Gladiator Costume Set",
    price: 42.99,
    originalPrice: 55.99,
    image: "https://m.media-amazon.com/images/I/81GyWJibfsL._AC_SX522_.jpg",
    images: [
      "https://m.media-amazon.com/images/I/81flDqHNAeL._AC_SX522_.jpg",
      "https://m.media-amazon.com/images/I/71HKzAtnu2L._AC_SX522_.jpg",
      "https://m.media-amazon.com/images/I/717oY3l4l-L._AC_SX522_.jpg",
      "https://m.media-amazon.com/images/I/A10i1wxzrfL._AC_SX522_.jpg",
      "https://m.media-amazon.com/images/I/71BxKDXKnoL._AC_SX522_.jpg",
    ],
    description:
      "Noble Medieval Roman Gladiator Toga Costume for Men, includes 1 White Tunic 1* Armor w/ Cape, 1 Pair of Shoulder Guards, 1 Pair of Armors, 1 Pair of Leg Guards.",
    category: "Men's Fashions",
    rating: 4.4,
    reviews: "1.3k",
    inStock: true,
    affiliateLink: "https://amzn.to/4l1uiPA",
  },
  {
    id: 17,
    name: "Aviator Sunglasses for Men",
    price: 13.42,
    originalPrice: 23.99,
    image: "https://m.media-amazon.com/images/I/71J0Y7b5GlL._AC_SX569_.jpg",
    images: [
      "https://m.media-amazon.com/images/I/81fyTbHYn9L._AC_SY550_.jpg",
      "https://m.media-amazon.com/images/I/61kf05cGX0L._AC_SY550_.jpg",
      "https://m.media-amazon.com/images/I/81bP6R9WhFL._AC_SY550_.jpg",
    ],
    description:
      "eye protection effectively filter & block glares. Designed for driving & outdoor activities;High-definition lens gives you a natural & clear vision;Sturdy & Shatterproof.",
    category: "Men's Accessories",
    rating: 4.5,
    reviews: "5.6k",
    inStock: true,
    affiliateLink: "https://amzn.to/4o525tT",
  },
  {
    id: 18,
    name: "Halloween Costumes for Women - White Collar Long Sleeve Black Dress",
    price: 32.99,
    originalPrice: 45.99,
    image: "https://m.media-amazon.com/images/I/61LH+BAkUHL._AC_SX679_.jpg",
    images: [
      "https://m.media-amazon.com/images/I/51Xk4jh2oAL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/51WiMFh77ML._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/51zNkfsNcaL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/41QTNV1bjML._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/51C7iof5MIL._AC_SX679_.jpg",
    ],
    description:
      "5Pcs Halloween costumes for women include: one long sleeve peter pan collar black dress,one indian women braided costume wig, one wig cap, one black knee socks, one black makeup lipstick. what you see is what you get.",
    category: "Women's Fashions",
    rating: 4.5,
    reviews: "687",
    inStock: true,
    affiliateLink: "https://amzn.to/46w7942",
  },
  {
    id: 19,
    name: "Halloween Costumes Woman Pumpkin Ghost Skeleton",
    price: 14.98,
    originalPrice: 24.9,
    image: "https://m.media-amazon.com/images/I/51FCpDi1+7L._AC_SX679_.jpg",
    images: [
      "https://m.media-amazon.com/images/I/61uvNr0omNL._AC_SY741_.jpg",
      "https://m.media-amazon.com/images/I/61dDV9RLLxL._AC_SY741_.jpg",
      "https://m.media-amazon.com/images/I/51iXCgweNcL._AC_SY741_.jpg",
      "https://m.media-amazon.com/images/I/5124No2-MAL._AC_SY741_.jpg",
      "https://m.media-amazon.com/images/I/51jJyq-cD7L._AC_SY741_.jpg",
    ],
    description:
      "95% Ployester, 5% Spandex; Comfortable, soft and lightweight fabric, comfortable wearing experience; Halloween costumes woman 2024, halloween costumes, women halloween costumes, skeleton costume adult women, halloween para halloween poncho for women.",
    category: "Women's Fashions",
    rating: 4.6,
    reviews: "49",
    inStock: true,
    affiliateLink: "https://amzn.to/3U1lQEL",
  },
  {
    id: 20,
    name: "Halloween Deluxe Adult Costume for Women",
    price: 28.99,
    originalPrice: 37.9,
    image: "https://m.media-amazon.com/images/I/71Mc+q1FUbL._AC_SX679_.jpg",
    images: [
      "https://m.media-amazon.com/images/I/61I4tpC3aKL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/51HlrfPQPRL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/51la0DbQwrL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/51LhzLJ43xL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/51gnGAB0YHL._AC_SX679_.jpg",
    ],
    description:
      "7Pcs Halloween costumes for women include one long sleeve turtleneck orange shirt, one red pleated skirt, one brown wig and one ,wig cap, one orange knee socks, one square black glasses and one magnifying glass. what you see is what you get.",
    category: "Women's Fashions",
    rating: 4.4,
    reviews: "573",
    inStock: true,
    affiliateLink: "https://amzn.to/45pzF6g",
  },
  {
    id: 21,
    name: "Black Cat Costumes, Cat Ears Headband Tail Paws Gloves Collar Set",
    price: 14.99,
    originalPrice: 24.99,
    image: "https://m.media-amazon.com/images/I/71q170NKGhL._AC_SX569_.jpg",
    images: [
      "https://m.media-amazon.com/images/I/81R0uMkkjZL._AC_SX522_.jpg",
      "https://m.media-amazon.com/images/I/819vTck6fJL._AC_SX522_.jpg",
    ],
    description:
      "Black Cat Halloween Costume - You will receive 1 x cat ears headband, 1 pair of cat paws Gloves, 1 x cat tail, and 1 x bell collar. Sufficient quantity and a nice cat costume combination to make you more charming.",
    category: "Women's Fashions",
    rating: 4.6,
    reviews: "73",
    inStock: true,
    affiliateLink: "https://amzn.to/3HcJKu2",
  },
  {
    id: 22,
    name: "Halloween Oversized T Shirts",
    price: 17.98,
    originalPrice: 23.96,
    image: "https://m.media-amazon.com/images/I/61bsQSIwT5L._AC_SX569_.jpg",
    images: [
      "https://m.media-amazon.com/images/I/8160n7F6kDL._AC_SY550_.jpg",
      "https://m.media-amazon.com/images/I/61J97-fagFL._AC_SY550_.jpg",
      "https://m.media-amazon.com/images/I/71GwVST9yuL._AC_SX425_.jpg",
      "https://m.media-amazon.com/images/I/71Gt6LlEppL._AC_SX466_.jpg",
    ],
    description:
      "Witch T Shirts Material: hey Didn't Burn Witches They Burned Women Witchy Feminist Oversized T-Shirts Tops is Made of Soft Cotton Blend,This Girls Will Be Girls Witch Feminist T Shirts for Women Shows Off Your Curves Perfectly,It's Casual and Comfortable,You Will Need Them All Over The Year.",
    category: "Women's Fashions",
    rating: 4.1,
    reviews: "33",
    inStock: true,
    affiliateLink: "https://amzn.to/4l42ytE",
  },
  {
    id: 23,
    name: "Women Halloween Shirt Funny Pumpkin Face",
    price: 11.04,
    originalPrice: 17.99,
    image: "https://m.media-amazon.com/images/I/61zvvzDTG2L._AC_SX425_.jpg",
    images: [
      "https://m.media-amazon.com/images/I/81Dpo9ryvRL._AC_SY550_.jpg",
      "https://m.media-amazon.com/images/I/61RwhVZDUnL._AC_SX425_.jpg",
      "https://m.media-amazon.com/images/I/51n6TTYNmIL._AC_SY550_.jpg",
    ],
    description:
      "This women halloween shirts are made of high quality materials, which brings you a soft touch and is very comfortable to wear.",
    category: "Women's Fashions",
    rating: 4.2,
    reviews: "142",
    inStock: true,
    affiliateLink: "https://amzn.to/3IS9koG",
  },
  {
    id: 24,
    name: "Women Halloween Dress Lace Flutter Sleeve",
    price: 19.99,
    originalPrice: 25.99,
    image: "https://m.media-amazon.com/images/I/71cSmU79Q7L._AC_SY445_.jpg",
    images: [
      "https://m.media-amazon.com/images/I/71JWgM7-DXL._AC_SY550_.jpg",
      "https://m.media-amazon.com/images/I/81NOFNQ7VJL._AC_SY550_.jpg",
      "https://m.media-amazon.com/images/I/71S-dQxa1gL._AC_SY550_.jpg",
      "https://m.media-amazon.com/images/I/71eod9iLquL._AC_SY550_.jpg",
    ],
    description:
      "The Black Lace Dress is Clearly Made for a Spooky Occasion. High Quality, Soft, Stretchy and Lightweight Materials are so Comfortable, Breathable, and Suitable to Wear all Day.",
    category: "Women's Fashions",
    rating: 4.5,
    reviews: "313",
    inStock: true,
    affiliateLink: "https://amzn.to/4mCkLQf",
  },
  {
    id: 25,
    name: "Witch Please Graphic Tees Tops",
    price: 8.99,
    originalPrice: 12.99,
    image: "https://m.media-amazon.com/images/I/61uCEjtHK2L._AC_SX466_.jpg",
    images: [],
    description:
      "Women Witch Outfit Halloween Shirt Graphic Tees Shirts with Sayings Halloween Matching Tees Funny Cute Casual Short Sleeve Round Neck.",
    category: "Women's Fashions",
    rating: 4.3,
    reviews: "668",
    inStock: true,
    affiliateLink: "https://amzn.to/3Hb2fix",
  },
  {
    id: 26,
    name: "Fall Casual Dress Sleeveless V Neck Gothic Dress",
    price: 29.74,
    originalPrice: 34.99,
    image: "https://m.media-amazon.com/images/I/61oQsOwHahL._AC_SY550_.jpg",
    images: [
      "https://m.media-amazon.com/images/I/81Q1N9jeNoL._AC_SY550_.jpg",
      "https://m.media-amazon.com/images/I/619pL3rXDHL._AC_SY550_.jpg",
    ],
    description:
      "You can explore through the variant colors. 95% Polyester, 5% Elastane Imported Pull On closure Machine Wash.",
    category: "Women's Fashions",
    rating: 4.5,
    reviews: "140",
    inStock: true,
    affiliateLink: "https://amzn.to/40FsYdK",
  },
  {
    id: 27,
    name: "Women Halloween Leggings Printed Stretchy",
    price: 9.99,
    originalPrice: 14.99,
    image: "https://m.media-amazon.com/images/I/61lZoOLHF8L._AC_SX522_.jpg",
    images: [
      "https://m.media-amazon.com/images/I/61aJrnyVdcL._AC_SX522_.jpg",
      "https://m.media-amazon.com/images/I/61qmF7OmxnL._AC_SX522_.jpg",
      "https://m.media-amazon.com/images/I/61sBkNT7SfL._AC_SX425_.jpg",
    ],
    description:
      "This Halloween Leggings Design Comes From the Dark Night of Halloween, Jack-o-lantern, Lace Spider Web, Sugar Skull, Castle Witch, Horror Nights, Bat, Pumpkin, Moon. These Funny Graphic Leggings Pattern is Easy to Catch People's Attention, Great Design Makes you Win People's Applause and Enjoy the Halloween Party.",
    category: "Women's Fashions",
    rating: 4.2,
    reviews: "310",
    inStock: true,
    affiliateLink: "https://amzn.to/45aw7DE",
  },
  {
    id: 28,
    name: "Skull Graphic T Shirts Long Sleeve Pullover Tops",
    price: 16.79,
    originalPrice: 29.99,
    image: "https://m.media-amazon.com/images/I/81gjmHxd9bL._AC_SX342_.jpg",
    images: [
      "https://m.media-amazon.com/images/I/81Fd-4pl97L._AC_SY550_.jpg",
      "https://m.media-amazon.com/images/I/81F0+453CcL._AC_SY550_.jpg",
      "https://m.media-amazon.com/images/I/81Fiy9XtxSL._AC_SY550_.jpg",
    ],
    description:
      "This halloween skull graphic sweatshirt features white skull or other different patterns on the center, loose-fitting design and hole design. The casual and slouchy street style makes you look like a cool girl.",
    category: "Women's Fashions",
    rating: 4.6,
    reviews: "2.7k",
    inStock: true,
    affiliateLink: "https://amzn.to/40J7KeZ",
  },
  {
    id: 29,
    name: "Boo Boo Crew T-Shirt Halloween Design",
    price: 11.89,
    originalPrice: 36.99,
    image: "https://m.media-amazon.com/images/I/61+Fzg-JmNL._AC_SX522_.jpg",
    images: [
      "https://m.media-amazon.com/images/I/71z5R1JU0iL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/61t-U-903XL._AC_SX522_.jpg",
      "https://m.media-amazon.com/images/I/91Of10XlkBL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/81Eh1TF+yOL._AC_SX522_.jpg",
    ],
    description:
      "This cute halloween nurse shirt is made of cotton blend. The fabric is soft and will not shrink significantly in the wash. We use sweat-absorbent clothing materials. Enjoy a smooth soft touch.",
    category: "Women's Fashions",
    rating: 4.4,
    reviews: "201",
    inStock: true,
    affiliateLink: "https://amzn.to/3TZe7ap",
  },
  {
    id: 30,
    name: "Cat Pumpkin Cardigan Long Sleeve",
    price: 19.99,
    originalPrice: 24.99,
    image: "https://m.media-amazon.com/images/I/61mjN0UkFnS._AC_SX522_.jpg",
    images: [
      "https://m.media-amazon.com/images/I/61lI2WIybbS._AC_SX522_.jpg",
      "https://m.media-amazon.com/images/I/61UQd2G+YES._AC_SX522_.jpg",
      "https://m.media-amazon.com/images/I/61OAvSr42LS._AC_SX522_.jpg",
    ],
    description:
      "Super soft cotton polyester women halloween cardigan, make you warm, beautiful, fashionable, sexy and elegant. This is a great plus size shirt casual Open Front Cardigan! The soft and breathable fabric keeps you cozy while showcasing your unique style, making it a perfect choice for the spooky season.",
    category: "Women's Fashions",
    rating: 4.0,
    reviews: "1.1k",
    inStock: true,
    affiliateLink: "https://amzn.to/3H93u1J",
  },
];
